---
- hosts: hana

  vars:
          ### OUTDATED ### 
          ### Need an Update ###
          # SAP-BASE-ROLE
          # can use defaults

          # sap-hana-preconfigure
          sap_hana_preconfigure_min_package_check: false
          sap_hana_preconfigure_reboot_after_update: false
          sap_hana_preconfigure_reboot_timeout: 600

          # SAP-Media Check
          sap_hana_mediacheck_serverpath: "vm30.tom.lan:/install"
          sap_hana_mediacheck_mountpoint: /install
          sap_hana_installdir: "{{ sap_hana_mediacheck_mountpoint + '/HANA_EXPRESS_20/DATA_UNITS/HDB_SERVER_LINUX_' + ansible_architecture| upper }}"

          # SAP HANA Hostagent:
          sap_hana_hostagent_archive: "{{ sap_hana_mediacheck_mountpoint + '/hostagent-7.21/SAPHOSTAGENT40_40-20009394.SAR' }}"
          #sap_hana_hostagent_archive: "{{ sap_hana_installdir + '/server/HOSTAGENT.TGZ' }}"
          #sap_hana_hostagent_unarchive_cmd: "tar --strip-components=3 -xzf "
          sap_sapadm_uid: 20202
          sap_sapsys_gid: 20202

          sap_sapadm_pw_clear: "MyS3cret!"
          sap_hana_hostagent_ssl_pw: "MyS3cret!"

          #id_group_shm: "30220"

  roles:
    - sap-base-settings
    - sap-hana-mediacheck
    - sap-hana-preconfigure
    - sap-hana-hostagent
