---

#- name: Execute HANA Host Agent SSL Configuration
# andbuick / 08.10.2017
# SAP NOTE 2130510  Version 3 / 28.06.2016 latest Host Agent 7.21
# SAP NOTE 1907566 Version 5 / 27.02.2017 latest documentation
# SAP NOTE 401162 Version 20 / 20.03.2017
# SAP NOTE 1292836 Version 6 / 18.12.2014
# SAP NOTE 1031096 Version 36 / 20.10.2015
#
# Vom SAP Host-Agent werden keine Linux-Kernel-Parameter geändert.
# Service in etc/service/saphostctrl Default Port 1128 SAP HANA & SAP NetWeaver Services SOAP/HTTP
# Service in etc/service/saphostctrls Default Port 1129 SAP HANA & SAP NetWeaver Services SOAP/HTTP
#
# Starten / Stoppen als Root (root permissions)
#
# Der Host-Agent muss immer in der aktuellsten Version vorgehalten werden: derzeit 7.21
# Installationsverzeichnis: /usr/sap/hostctrl
# https://wiki.scn.sap.com/wiki/display/ATopics/SAP+Host+Agent+-+Frequently+Asked+Questions

# The following lines are a handler script
# moved to handlerr/tasks.yml
#- name: Restart HostAgent
#  shell: /usr/sap/hostctrl/exe/saphostexec -restart
#  listen: "Execute HANA Host Agent SSL Configuration"

# Installation of SAP HANA Host Agent
# Need this for ScaleOut Enviornments
# Did not work with ssh under SLES12, RHEL6, RHEL7
# https://access.redhat.com/solutions/1370033

- name: Installation File SAP HANA Host Agent
  template:
    src: preconfigure_sap_install_saphostagent.sh.j2
    dest: /usr/local/bin/preconfigure_sap_install_saphostagent.sh
    mode: 0755

- name: Install SAP HANA Host Agent
  shell: /usr/local/bin/preconfigure_sap_install_saphostagent.sh
  args:
    creates: /usr/sap/hostctrl/exe/saphostexec

# Setup sap hana Hostagent SSL
# http://help.sap.com/saphelp_nw73ehp1/helpdata/en/8d/12f7b9244b44219bd14d619d3a2123/content.htm
# Based on RHEL Documentation https://access.redhat.com/solutions/1370033
- name: Create directory for SAP HANA Hostagent SSL Configuration
  file:
    path: /usr/sap/hostctrl/exe/sec
    state: directory
    mode: 0755
    owner: sapadm
    group: sapsys

- name: Deployfile for HANA Host Agent SSL Configuration
  template:
    src: preconfigure_sap_install_sslforsaphostagent.sh.j2
    dest: /usr/local/bin/preconfigure_sap_install_sslforsaphostagent.sh
    mode: 0755


- name: Ensure SSL is configured for saphostagent
  shell: /usr/local/bin/preconfigure_sap_install_sslforsaphostagent.sh
  notify: "Restart HostAgent"
  args:
    creates: /usr/sap/hostctrl/exe/sec/SAPSSLS.pse

- name: Change user for SAPSSLS.pse file for SAP Host Agent
  file:
    path: /usr/sap/hostctrl/exe/sec/SAPSSLS.pse
    state: file
    owner: sapadm
    group: sapsys

...
