---

- name: Copy RPM based SAPHOSTAGENT to the target host
  copy:
    src: "{{ sap_hostagent_rpm_local_path }}/{{ sap_hostagent_rpm_file_name }}"
    dest: "{{ sap_hostagent_agent_tmp_directory }}/{{ sap_hostagent_rpm_file_name }}"

- name: Ensure RPM file is installed
  yum:
    name: "{{ sap_hostagent_agent_tmp_directory }}/{{ sap_hostagent_rpm_file_name }}"
    state: present