---

# Execute common pre installation tasks
- import_tasks: common_pre.yml

# Deploy SAPHOSTAGENT using RPM file
- import_tasks: deploy_rpm.yml
  when: installation_type == "rpm"

# Deploy SAPHOSTAGENT using SAR file
- import_tasks: deploy_sar.yml
  when: installation_type == "sar"

# Deploy SAPHOSTAGENT using SAP Installation Bundle
- import_tasks: deploy_bundle.yml
  when: installation_type == "bundle"

# Execute common post installation tasks
- import_tasks: common_post.yml
